name: Deploy to production
on:
#  push:
#    branches:
#      - master
  workflow_dispatch:
    inputs:
      release:
        description: Name of release to deploy
        required: true
        default: v1.0.0

jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: '12'
    - name: Download the release artifact
      uses: actions/download-artifact@v2
      with:
        name: release-${{ github.event.inputs.release }}
        path: .serverless
    - name: Directory listing
      run: ls .serverless
    - name: check README
      run: cat .serverless/README.md
#    - name: serverless deploy
#      uses: serverless/github-action@master
#      with:
#        args: deploy --stage=prod --package=.serverless
#      env:
#        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
